# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='django_types.proto',
  package='',
  serialized_pb='\n\x12\x64jango_types.proto\"M\n\x04\x44\x61te\x12\x15\n\x04time\x18\x81\x80\x02 \x01(\x0b\x32\x05.Time\x12\r\n\x03\x64\x61y\x18\x82\x80\x02 \x02(\x05\x12\x0f\n\x05month\x18\x83\x80\x02 \x02(\x05\x12\x0e\n\x04year\x18\x84\x80\x02 \x02(\x05\":\n\x04Time\x12\x0e\n\x04hour\x18\x81\x80\x02 \x02(\x05\x12\x10\n\x06minute\x18\x82\x80\x02 \x02(\x05\x12\x10\n\x06second\x18\x83\x80\x02 \x02(\x05\x42\x1a\n\x12org.lcogt.protobuf\x88\x01\x01\x90\x01\x01')




_DATE = descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='Date.time', index=0,
      number=32769, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='day', full_name='Date.day', index=1,
      number=32770, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='month', full_name='Date.month', index=2,
      number=32771, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year', full_name='Date.year', index=3,
      number=32772, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=99,
)


_TIME = descriptor.Descriptor(
  name='Time',
  full_name='Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hour', full_name='Time.hour', index=0,
      number=32769, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='minute', full_name='Time.minute', index=1,
      number=32770, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='second', full_name='Time.second', index=2,
      number=32771, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=101,
  serialized_end=159,
)

_DATE.fields_by_name['time'].message_type = _TIME
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Time'] = _TIME

class Date(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATE
  
  # @@protoc_insertion_point(class_scope:Date)

class Time(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIME
  
  # @@protoc_insertion_point(class_scope:Time)

# @@protoc_insertion_point(module_scope)
